var hihat = new Audio('drum-sounds/hihat.wav')
var tom = new Audio('drum-sounds/tom.wav')
var openhat = new Audio('drum-sounds/openhat.wav')
var boom = new Audio('drum-sounds/boom.wav')
var clap = new Audio('drum-sounds/clap.wav')
var kick = new Audio('drum-sounds/kick.wav')
var ride = new Audio('drum-sounds/ride.wav')
var snare = new Audio('drum-sounds/snare.wav')
var tink = new Audio('drum-sounds/tink.wav')
var hihatbutton = document.getElementById('hihatbutton')
var tombutton = document.getElementById('tombutton')
var openhatbutton = document.getElementById('openhatbutton')
var boombutton = document.getElementById('boombutton')
var clapbutton = document.getElementById('clapbutton')
var kickbutton = document.getElementById('kickbutton')
var ridebutton = document.getElementById('ridebutton')
var snarebutton = document.getElementById('snarebutton')
var tinkbutton = document.getElementById('tinkbutton')
hihatbutton.addEventListener('mouseenter', function() {
  console.log('hi hat yay!')
  hihat.play()
})
tombutton.addEventListener('mouseenter', function() {
  console.log('tom sound yay')
  tom.play()
})
openhatbutton.addEventListener('mouseenter', function() {
  console.log('open hat sound yay')
  openhat.play()
})
boombutton.addEventListener('mouseenter', function() {
  console.log('BOOOM')
  boom.play()
})
clapbutton.addEventListener('mouseenter', function() {
  console.log('clap sound yay')
  clap.play()
})
kickbutton.addEventListener('mouseenter', function() {
  console.log('kick sound yay')
  kick.play()
})
ridebutton.addEventListener('mouseenter', function() {
  console.log('ride sound yay')
  ride.play()
})
snarebutton.addEventListener('mouseenter', function() {
  console.log('snare sound yay')
  snare.play()
})
tinkbutton.addEventListener('mouseenter', function() {
  console.log('tink sound yay')
  tink.play()
})
